% filter for usage in createcsvfromdata

function Hd = filt50hz
%50HZFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 28-Jan-2016 19:37:06

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 160;  % Sampling Frequency

N      = 200;  % Order
Fpass1 = 47;   % First Passband Frequency
Fstop1 = 49;   % First Stopband Frequency
Fstop2 = 51;   % Second Stopband Frequency
Fpass2 = 53;   % Second Passband Frequency
Wpass1 = 1;    % First Passband Weight
Wstop  = 1;    % Stopband Weight
Wpass2 = 1;    % Second Passband Weight
dens   = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 Fs/2]/(Fs/2), [1 1 0 0 1 ...
           1], [Wpass1 Wstop Wpass2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
