% filter for usage in createcsvfromdata

function Hd = mylowpassfilt
%MYLOWPASSFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 28-Jan-2016 17:51:59

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 160;  % Sampling Frequency

Fpass = 60;              % Passband Frequency
Fstop = 79;              % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
